spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
   '[org.springframework.web]': warn

#To disable the swagger UI Access
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: false


